### PR TITLE
Add validation on adding device that is already created

### PR DESCRIPTION
**Pull request by arielireni**
This PR solves issue #41

Signed-off-by: arielireni <aireni@redhat.com>

### CODE REVIEW

**Review by eloycoto — CHANGES_REQUESTED** [review]
This should have test, no?

**Comment by arielireni** [comment]
@eloycoto  Yes, I'll add tests in the following PR :)

**Comment by arielireni** [comment]
@eloycoto This PR solves issue #41, where the problem is that if we try to run: 
```
./bin/flotta add device -n device1
```
and `device1` already exists, then the command will finish with an error, but the bug here is that when creating a container fails (as part of the `add device` command), the device that was already registered will be deleted, after running the command above (even if it failed).
So, I agree that we need to add tests for trying to create an already existing resource but this PR solves another problem, so maybe I'll post a separate PR with the new tests? WDYT?

**Comment by pkliczewski** [comment]
@eloycoto please take a look

**Review by gciavarrini — APPROVED** [review]
lgtm

**Comment by gciavarrini** [comment]
According to @eloycoto commment
>  Fix the fmt.Sprintf and I'm happy to merge it.

I'll merge this PR

**Pull request merged**
